### ISSUE TITLE
Create Passwall CLI

### ISSUE THREAD

**Issue by shara-turic** [passwall/passwall-server#180]
I think passwall should have their cli app for more options for users

like

1. Passwall Desktop
2. Passwall Extension
3. Passwall CLI

and what about using **[GraphQL](https://graphql.org)** as dataloader, graphql is powerful & easy

I hope you will make it 🙏

**Comment by shara-turic** [comment]
and what abount using **[GraphQL](https://graphql.org)** as dataloader, graphql is powerful & easy

**Comment by shara-turic** [comment]
I'll close this issue because there is no response

**Comment by apiote** [comment]
Hi,
shameless plug but I'm adapting my cli which I initially wrote to support Nextcloud. I need a cli because I don't use neither FF not Chrome at home and there's no release of Passwall Desktop for musl and building doesn't work (probably because neither node-lts, nor node-stable is a compatible version—I don't know node—and nvm doesn't work with musl).

https://git.apiote.xyz/next-eeze.git is completely unofficial, no-warranty, and best-effort at most. Progress is slow because Passwall API documentation is wrong or missing in most parts, and I have to discover proper endpoints, parameters and which key encrypts what. So the latest WIP commits with authentication and listing passwords are not yet pushed. I'll probably add editing passwords later and focus first on reading them from server.
